#!/bin/bash -u

cd ..
make && \
sudo ./dynmhs \
   --interface enp0s3:1000 \
   --interface enp0s8:2000 \
   --interface enp0s9:3000 \
   --interface enp0s10:4000 \
   --loglevel 0

ip rule show ; ip -6 rule show
