.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/dynmhs/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd December 13, 2024
.Dt dynmhs 1
.Os dynmhs
.\" ###### Name #############################################################
.Sh NAME
.Nm dynmhs
.Nd Dynamic Multi-Homing Setup (DynMHS)
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm dynmhs
.Op Fl Z Ar on|off | Fl Fl logcolor Ar on|off
.Op Fl O Ar file | Fl Fl logfile Ar file
.Op Fl q | Fl Fl quiet
.Op Fl v | Fl Fl verbose
.Op Fl I Ar interface:table_id | Fl Fl interface Ar interface:table_id
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm dynmhs
dynamically sets up IP routing rules, to allow using multiple
network connections simultaneously. That is, for each relevant network
interface, a separate routing table is created and maintained. For each
source address of a network interface managed by DynMHS, routing rules
are maintained to point to the corresponding routing table. Software
binding to a specific interface address can then use a specific
network. In addition, multi-homing-capable network protocols like the
Multi-Path TCP (MPTCP) or the Stream Control Transmission Protocol (SCTP)
can take advantage of multi-homing for redundancy and load balancing.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument may be provided:
.Bl -tag -width indent
.It Fl L Ar level | Fl Fl loglevel Ar level
Sets the minimum logging level to the provided value: 0=trace, 1=debug, 2=info, 3=warning, 4=error, 5=fatal.
.It Fl Z Ar on|off | Fl Fl logcolor Ar on|off
Enables (on) or disables (off) the usage of ANSI color escape sequences to colorise the log output according to its level.
.It Fl O Ar file | Fl Fl logfile Ar file
Sets a file name for appending the log output to. If a file is set, no log output is made to the console.
Otherwise, all log output will be written to the console.
.It Fl q | Fl Fl quiet
Sets the minimum logging level to 3 (warning).
.It Fl v | Fl Fl verbose
Sets the minimum logging level to 0 (trace).
.It Fl I Ar interface:table_id | Fl Fl interface Ar interface:table_id
Sets an interface and the corresponding routing table ID. All routing entries referring to this interface will be cloned from the main routing table. All IP addresses of the interface will get an IP rule pointing to the corresponding routing table.
The parameter can be repeated to provide multiple interfaces.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It dynmhs --version
.It sudo dynmhs --interface eno1:1000 --interface eno2:1002 --loglevel 0
.It sudo dynmhs -I ethernet:1000 -I telia:2000 -I telenor:3000 --loglevel 2
.It sudo dynmhs -I ethernet:1000 -I telia:2000 -I telenor:3000 --logcolor off
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/dynmhs
.br
mailto://dreibh@simula.no
.br
